name: coffee_store_ui
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  badges: ^2.0.2
  carousel_pro: ^1.0.0
  cloud_firestore: ^3.1.6
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  flutter_feather_icons: ^2.0.0+1
  flutter_icons: ^1.1.0
  flutter_screenutil: ^5.0.3
  flutter_staggered_grid_view: ^0.4.0
  google_fonts: ^2.2.0
  provider: ^6.0.2
  flutter_local_notifications: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
